name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: npm run build  # Adjust this command based on your static site generator

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GSEC_TOKEN }}
        publish_dir: ./public  # Adjust this path based on where your build output is
#Access your app via https://your-username.github.io/repository-name/
